### ISSUE TITLE
Improve docs, add examples

### ISSUE THREAD

**Issue by subversivo58** [xcatliu/mobi.css#16]
Your site is unavaliable for reference docs, guides or examples about this framwork.

Sugest:

> **demo** path in project folder
> 
> **Docs.md** for reference framework
> 
> **GitHub Page** for project and documentation **examples**

I like the idea of this framework it is very succinct.

**Comment by xcatliu** [comment]
Hi @subversivo58 , glad to hear that you are interesting in this project.
Sorry I don't get the point of your suggest. Are you suggesting that I should add a demo directory and then separate the examples from the current homepage?

**Comment by subversivo58** [comment]
Your page was not online a few minutes ago.
Yes I suggested creating html pages demonstration in the project folder (on demo path) or GitHub page.

**Comment by xcatliu** [comment]
Is it avaliable now? I changed the DNS and I think it may take some time for it to become effective. Sorry about that.

Actually I do think the current Homepage is a little chaotic and I have a plan to improve it. I'll take your advice to add an page for examples.

Thanks!

**Comment by xcatliu** [comment]
Redesigned website.
http://getmobicss.com

Will create another task for adding examples
