### ISSUE TITLE
http://getmobicss.com/ does not work

### ISSUE THREAD

**Issue by ogoudron** [xcatliu/mobi.css#17]
Hello,

http://getmobicss.com/ show a landing page due to domain name not renewed.

**Comment by xcatliu** [comment]
Sorry for that :(

I updated DNS to help Chinese people view this page without the need of climbing over the GFW. The DNS is already updated for 4 hours, the [ping test](https://tools.pingdom.com/#!/BYJUb/getmobicss.com) [[2](http://ping.chinaz.com/?host=getmobicss.com&linetype=%E7%94%B5%E4%BF%A1%2C%E5%A4%9A%E7%BA%BF%2C%E8%81%94%E9%80%9A%2C%E7%A7%BB%E5%8A%A8%2C%E6%B5%B7%E5%A4%96)] said the site is available worldwild now, but it seems that [some people](https://github.com/xcatliu/mobi.css/issues/16) may have trouble to touch the website.

I've created a mirror site for you: http://getmobicss.xcatliu.com/

Hope this could help you. Thanks for your feedback!

**Comment by xcatliu** [comment]
Another option, please [clear your DNS cache](https://www.google.com/search?q=clear%20dns%20cache&rct=j#newwindow=1&q=how+to+clear+dns+cache) then try to visit http://getmobicss.com/ again, I think that would work

**Comment by xcatliu** [comment]
Please let me know when http://getmobicss.com/ is working

**Comment by ogoudron** [comment]
on mac, used "dscacheutil -flushcache" and tried but does not work.
I will try again in one hour.

**Comment by xcatliu** [comment]
Thanks, dose http://getmobicss.xcatliu.com/ work?

**Comment by ogoudron** [comment]
http://getmobicss.xcatliu.com/ does work.

http://getmobicss.com/ does not work from my network even after rebooting my Internet Box and the computer used for the test but i was able to ping it from a server hosted somewhere else.

**Comment by xcatliu** [comment]
Sorry to hear that.
I think the only way is to wait for the DNS cache in your location expired :(

I'll keep http://getmobicss.xcatliu.com/ as a backup site for people who cannot ping http://getmobicss.com/
You can visit http://getmobicss.xcatliu.com/ for the documentation.

Thanks!

**Comment by alexpricedev** [comment]
http://getmobicss.com/ works for me. This issue can be closed?

**Comment by xcatliu** [comment]
@alexpriceonline Thanks for your feedback! As there are no other people have this issue, I think we can close it now. I'll keep http://getmobicss.xcatliu.com/ as a backup for a few days, then set it redirect to http://getmobicss.com/
