### ISSUE TITLE
Collapse columns

### ISSUE THREAD

**Issue by subversivo58** [xcatliu/mobi.css#18]
Collapse columns in small screens (e.g: < 500px) ?

The visibility in mobile devices is affected since the columns do not automatically expand into a single row.

<img src="https://cloud.githubusercontent.com/assets/6475273/18219202/44b9dd0a-713e-11e6-826e-36613b195274.png" width="270">

<img src="https://cloud.githubusercontent.com/assets/6475273/18219217/5f0f19cc-713e-11e6-8fcc-26c7eea7d523.png" width="270">

**Comment by xcatliu** [comment]
Thanks for your feedback!
Actually this is part of my design.

Unlike other responsive framework, Mobi.css is designed for mobile devices.
In my opinion, A designer should think about the design of small screen (The smallest is 320px for iPhone 5), and the design should looks the same as large screen (i.e. 414px for iPhone 6s).

So if one `row` cannot accommodate your `col`s on small devices, maybe you should redesign it.

If you want to implement a wrap-able `row`, you can manually set `flex-wrap: wrap` to `row`

Thanks!

**Comment by subversivo58** [comment]
Excuse me. I'm terrible with front-end but logic tells me that if I create a line with two columns example:

A 1-4 column to display an image and a single column that had occupied the rest of the line to display a description.

If the framework is focused on mobile when I open a lower resolution (mobile) it should collapse these columns to display the image and below the description. Would not it?

Regardless of how you would treat your css it should be automatic in the framework or not?

**Comment by subversivo58** [comment]
Sorry, my poor englis

**Comment by xcatliu** [comment]
> A 1-4 column to display an image and a single column that had occupied the rest of the line to display a description.
> 
> If the framework is focused on mobile when I open a lower resolution (mobile) it should collapse these columns to display the image and below the description. Would not it?

Most of css framework follows this rule. But I don't think that is the right way.

When you are using native apps, such as WeChat, Twitter, WhatsApp, etc. They all have an image-content design (actually it's [media object in Bootstrap](https://getbootstrap.com/components/#media)). But none of them will show two rows in small device.

So my suggestion is you should design your website for small devices (like 320px width for iPhone 5), and for large devices, it should looks the same with small devices.

**Comment by subversivo58** [comment]
ok, thanks.
