### ISSUE TITLE
Container and container-side not direct in body cause container-side not on side

### ISSUE THREAD

**Issue by guyskk** [xcatliu/mobi.css#20]
Container and container-side not direct in body cause container-side not on the side, it's on the top.

``` html
<body>
    <div id="app">
        <div class="container-side">
            <p>Scan to view on mobile</p>
            <img src="path/to/qrcode.png" />
        </div>
        <div class="container">
            <h1>Mobi.css</h1>
        </div>
    </div>
</body>
```

**Comment by xcatliu** [comment]
Hmm, that's a problem, it's a bad design that `container` and `container-side` must be the child of `body`.
And also bad to set the `body` element to `display:flex`.

I'll think about a new idea.

A related issue: #19 

Thanks!

**Comment by xcatliu** [comment]
Hi @guyskk 

I've created a pull-request for this: [docs.md](https://github.com/xcatliu/mobi.css/pull/21/files#diff-812f46120405b1808a1087441b5dc694L57)

Please take a look if you have time, any advice is welcome.

Thanks!
