### ISSUE TITLE
国人开源为啥不出中文版说明？

### ISSUE THREAD

**Issue by SFLAQiu** [xcatliu/mobi.css#29]

**Comment by xcatliu** [comment]
因为感觉现在 API 可能还会有改动，没有精力维护两份文档。
等 1.0.0 发布（应该在 9 月份之内）之后我会第一时间写出中文文档。

感谢支持！

**Comment by RaineySpace** [comment]
@SFLAQiu 很想借用尤大的一句话回答，[为啥我要牺牲陪老婆孩子的时间来替你省学英语的时间？](https://www.zhihu.com/question/49884331/answer/118492169?from=profile_answer_card)

**Comment by xcatliu** [comment]
@XueRainey @SFLAQiu 文档频繁更新的时候，同步英文文档和中文文档是一件头疼的事儿。确实没精力去维护，不如先把时间花在做好项目上。感谢支持和理解！

**Comment by multics** [comment]
凭啥要出中文？或者为啥你不来感谢作者或者翻译文档而只是抱怨？有这时间应该去学英文

**Comment by SFLAQiu** [comment]
1.是建议不是抱怨
2.提供中文文档的目的是可以让国内开发者更好的理解和使用框架
3.国人开源没有中文文档，总感觉缺少点什么

**Comment by aborn** [comment]
英文是必修语言，不想学英文，那视野只会局限于中文世界。

**Comment by RockyAo** [comment]
那你为啥不用中文编程？

**Comment by LPicker** [comment]
虽然我们都必须学习英语，但是毕竟母语是中文，英文再好，都没有中文看着舒服、流畅、省时、省力。

**Comment by zhangyuefang** [comment]
@xcatliu 群个中文QQ交流群吧。

**Comment by xcatliu** [comment]
@zhangyuefang 暂时没有精力维护 QQ 群，我会先集中精力把 1.0.0 做出来。

**Comment by zhangyuefang** [comment]
@xcatliu 好，期待1.0.0！

**Comment by kpman** [comment]
When you decide to open source your project, a lot of people will start watching and using your project.
Keep going! Waiting for `v1.0.0`!

**Comment by xcatliu** [comment]
@kpman I'm testing and reconstructing documentations now. I'll publish `v1.0.0` before Sep 30, you can watch https://github.com/xcatliu/mobi.css/milestone/1 for details.

Thanks for your supporting!

**Comment by vicvinc** [comment]
看了下这哥们的GIT，其中一个open的PR让MS的人汗颜不已，感觉作者可以直接close这类的PR，浪费时间。

**Comment by xgz123** [comment]
虽然英文阅读是必修的, 但是中文看起来更舒服也是事实. 作者精力有限, 大家可以共同完善.

**Comment by 5vbear** [comment]
期待1.0。要不开一个文档项目，拉几个有精力的contributor一起完善?（另外可以把支付宝或微信二维码放下面赚点咖啡钱的☺）

**Comment by xcatliu** [comment]
@omixk @5vbear 
目前 http://getmobicss.com 网站不准备另开一个项目，因为在同一个项目中方便调试 Mobi.css 的样式。
zh-cn 正在进行中，因为是用 hexo 生成的网页，所以需要一些基础建设，等基础建设完成后（before 2016-09-20），欢迎一起完善中文文档。

@5vbear 本来没想着放微信支付宝二维码，因为觉得连 1.0.0 都还没发布呢。不过后来觉得能够赚点咖啡钱也不错，得到大家的支持项目一定能更好的发展。
感谢大家的支持！

**Comment by Kimi-Gao** [comment]
建议作者还是要有中文文档，毕竟（猜测）大部分使用该框架的用户母语还是中文吧，用英文还是中文主要还是因地制宜，以目标用户为上，不能一味追求英文，有些思想可能略有偏激，当然如果自己本身英文能力很好，视野也会更开阔，严于律己宽以待人。

**Comment by xcatliu** [comment]
@SFLAQiu @LPicker @omixk @5vbear @muwenzi
中文的基础建设完成了，目前我翻译了 index，感兴趣的可以一起来 😄
官方网站中文版： http://getmobicss.com/zh-cn/
中文文档源码： https://github.com/xcatliu/mobi.css/tree/master/site/source/zh-cn

**Comment by liuhuanzhu** [comment]
期待正式版。希望有时间出一份中文文档

**Comment by tanket** [comment]
咋说呢，中国人做软件，不想先中文文档，因为主要针对外国人使用。而中国人用软件呢，也喜欢用外国人的，感觉中国人自己搞的东西不可靠。归结起来就是不管是中国的作者，还是使用者，都喜欢优先考虑外国人。

**Comment by xcatliu** [comment]
中文文档已完成 http://getmobicss.com/zh-cn/

**Comment by zhangyuefang** [comment]
@xcatliu 好，非常感谢！
