### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by jiaoben** [xcatliu/mobi.css#32]
表单中对iphone4兼容性不太好，如果能够解决一下就更好了

**Comment by xcatliu** [comment]
感谢反馈，手头暂时没有 iPhone4 设备，可以先截个图看看大概是什么样子吗？

**Comment by jiaoben** [comment]
![image](https://cloud.githubusercontent.com/assets/2520864/18297266/e6fc2b26-74e1-11e6-9f93-18684f5f5c9b.png)

**Comment by xcatliu** [comment]
多谢，看上去是 flexbox 的问题，我先调研一下看 iPhone4 上的问题好不好解决

**Comment by vvenv** [comment]
建议无须考虑支持 iPhone 4，马上淘汰了

**Comment by vicvinc** [comment]
同建议，现在标准的实现这么多，都要支持会累死人的

**Comment by xcatliu** [comment]
不准备在 iPhone 4 上调试了。
