### ISSUE TITLE
Why pull-request always failed?

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/mobi.css#38]
https://travis-ci.org/xcatliu/mobi.css/builds/158198786

**Comment by cht8687** [comment]
I checked the [build log](https://travis-ci.org/GoogleCloudPlatform/gcloud-node-todos/builds/35375406) and found `iv` is undefined.

I checked https://www.openssl.org/docs/manmaster/apps/enc.html,

it seems that 'the actual IV to use: this must be represented as a string comprised only of hex digits. When only the key is specified using the -K option, the IV must explicitly be defined.'

( I am not an openssl expert, but will this help? )

---updated-----
it appears that, OpenSSL implementation of ASE requires IV to be the same size as the block size.
if we leave this empty, it will randomly met the needs and perform the build.
