### ISSUE TITLE
Suggest to rename mt-15 and mt-30

### ISSUE THREAD

**Issue by J-F-Liu** [xcatliu/mobi.css#43]
Use gap, double-gag or small-gap, big-gap. This is easier to understand and consistent with naming style of other class names. Furthermore, the gap height can be changed in variable and not equal to 15px.

**Comment by xcatliu** [comment]
Your suggestion make sense.
Actually we have [`$width-gap`](https://github.com/xcatliu/mobi.css/blob/master/src/_variables.scss#L65) as a variable.
User may customize their `$width-gap` then `mt-15` will not be `15px`.

**Comment by xcatliu** [comment]
But `gap` or `double-gap` don't mean margin to top, maybe we can use `mt-0`, `mt-gap`, `mt-double-gap`?

Any other ideas?

**Comment by J-F-Liu** [comment]
How about vertical-gap, vertical-big-gap?
margin-top: 0 is the default value and margins are not inherited, so mt-0 is not require.

**Comment by xcatliu** [comment]
That sounds good :+1:

**Comment by xcatliu** [comment]
I'm going to rename it to `top-gap` and `top-gap-big` duo to following reasons:
1. `top` is easily to type than `vertical`, and more semantic than `vertical` -- we only set `margin-top`
2. It's better to follow this rule: [`All variables need to be named as ${rule}-${element}-${modifier}`](https://github.com/xcatliu/mobi.css/blob/master/src/_variables.scss#L6), so I put `big` at end

**Comment by xcatliu** [comment]
Added `top-gap-0`
