### ISSUE TITLE
Issue about row, col and flex-left

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/mobi.css#48]
`row` and `flex-left` is kind of overlap.
And it's not convenient to use `col` in `flex-left`.

Why `row` need to have `margin-left: -15px`?

Maybe we need to redesign it.

**Comment by gitlsl** [comment]
bootstrap  的 .row 就是 -15px  不然 第一个 col会进去15px。。

**Comment by gitlsl** [comment]
bootstrap  的 .row 就是 -15px  不然 第一个 col会进去15px。。

**Comment by xcatliu** [comment]
第一个可以用 first-child 解决。
可以参考下其他的框架
http://purecss.io/grids/
http://getskeleton.com/
都没有 -15px
col 也没有 padding

**Comment by xcatliu** [comment]
- Rename `col` to `unit`
- Add `units-gap`, `unit-0`, and `flex-vertical`

http://getmobicss.com/reference/#Flexbox
