### ISSUE TITLE
Vertical alignment on select menus

### ISSUE THREAD

**Issue by 3zzy** [xcatliu/mobi.css#49]
![Imgur](http://i.imgur.com/S9Hl1Sm.png)

Chrome 53, El Capitan

**Comment by xcatliu** [comment]
Currentlly I don't have MacBook 😭 
If an issue doesn't block the display, I'll fix it after I publish v1.0.0

Thanks!

**Comment by xcatliu** [comment]
@hxlniada please help fix this issue, thanks!
