### ISSUE TITLE
how to make item in container diplay in vertical

### ISSUE THREAD

**Issue by zerofront** [xcatliu/mobi.css#50]
How to make item in container display in vertical??
if we want to make item in container dispaly in vertical and item can wrap when the  height of container is limited .
**but uc browser for android can not perform true!!**
**because uc browser for android only supports the old flexbox specification and does not support wrapping.**

eg:  <.ul><.li class="first item":>1 <./li><.li>2<./li><.li>3<./li><.li>4<./li><.li>5<./li><.li>6<./li><.li>7<./li><.li>8<./li><.li>9<./li><./ul>
     ul {display:flex;flex-flow:column wrap;justify-content:flex-start;height:100px;overflow-x:auto}
     li {width:50px;height:50px}
    .first item {width:80px; 100px;}

即父元素高度限定，宽度根据子元素数量自适应。子元素从上到下竖直排列，当父元素高度不够的时候换下一列。这种布局在uc 浏览器 安卓版本无法实现，原因是安卓UC内核不支持flex布局的wrap。请问这个项目有针对这个垂直布局进行UC安卓端的适配吗？

**Comment by xcatliu** [comment]
目前已支持垂直布局的 Flexbox http://getmobicss.com/zh-cn/docs/#垂直-Flex-布局
但是在 UC 浏览器中还有问题。
我将关闭此 issue，UC 浏览器的问题统一在 #6 中处理。
