### ISSUE TITLE
http://getmobicss.com 无法访问

### ISSUE THREAD

**Issue by xuanye** [xcatliu/mobi.css#51]
无法访问了，为啥不用github，而用coding，coding多久没人访问就自动关闭了

**Comment by xcatliu** [comment]
感谢反馈，国内会访问 coding，国外还是 github。

我先改成 github page，之后有需要的话在把国内的改成 qiniu 吧

**Comment by xcatliu** [comment]
已切换

**Comment by xcatliu** [comment]
It should work now.

**Comment by xcatliu** [comment]
qiniu 的改动下次我会另起 issue
