### ISSUE TITLE
感觉可以对尺寸进行统一一下的说

### ISSUE THREAD

**Issue by wolfan** [xcatliu/mobi.css#65]
感觉尺寸单位并不是很统一吖，既然是用在Mobile上，为什么不把所有的尺寸单位统一使用vw呐。
还有 html 定义个font-size: 10px 是什么用的呐，老白菜表示不堪其用吖。。。。

**Comment by xcatliu** [comment]
感谢你的建议！
单位没统一确实带来一些问题，打算在 2.0 的时候解决。
html 10px 是为了方便 rem 的使用

**Comment by wolfan** [comment]
现在的好像不用设置一个基础就能直接用rem了吧，会自动又系统默认大小为基础的样，好像……

**Comment by hxlniada** [comment]
@wolfan http://caniuse.com/#search=vw
vw兼容性不好啊
html的font-size设置为10px还一个好处是好计算，不然单位换算麻烦

**Comment by xcatliu** [comment]
已更新到 v3.0.0，在 http://getmobicss.com/docs/variables.html 有说明
