### ISSUE TITLE
Communities for Mobi.css

### ISSUE THREAD

**Issue by xcatliu** [xcatliu/mobi.css#80]
In Mobi.css@2.0.0 , we will [add theme system](https://github.com/xcatliu/mobi.css/issues/39).
Mobi.css will be more open and ecological in the future.

So we are considering to take a series of actions to build the communities for Mobi.css:

- [x] Create a new [GitHub organization](https://github.com/mobi-css) for Mobi.css
- [x] Move related projects to the Mobi.css organization
- [x] Create a [twitter account for Mobi.css](https://twitter.com/mobi_css)
- [x] Create a [Gitter community for Mobi.css](https://gitter.im/mobi-css)
- [x] Add a blog system for Mobi.css

Do you have any other ideas?

**Comment by cht8687** [comment]
Creating Github organization is really a good idea.
we can latter make more demo projects using Mobi.css.

**Comment by Systemmanic** [comment]
GitHub pages for blogging? 

Seems like we can choose our own theming system so it can use mobi.css instead of bootstrap.

**Comment by xcatliu** [comment]
@dkanejs Currently I've registered a medium account https://medium.com/@mobi_css , I think medium can do a good job at SEO.

Later I'll create a blog repo for Mobi.css - after I complete the development of Mobi.css v2.0.0-alpha

Both Jekyll or Hexo can be a good choice.

Actually I've craeted a theme for hexo months ago: https://github.com/xcatliu/hexo-theme-mobi.css

**Comment by xcatliu** [comment]
Use medium for blogging
