### ISSUE TITLE
More themes?

### ISSUE THREAD

**Issue by Systemmanic** [xcatliu/mobi.css#84]
Lot's of other frameworks have many themes available by default. I often browse them for ideas when creating my own, and sometimes the ones provided are good enough. Its good to just try them out when developing, etc to see how my site looks.

Was thinking about creating some themes based on popular colour pallets. 

Good idea?

**Comment by xcatliu** [comment]
Agreed, we can do it after we finished the mobi.css v2.0.0-alpha
