### ISSUE TITLE
[Suggestion] For the consistency of gap control, cloud add class `units-gap-0`

### ISSUE THREAD

**Issue by zheeeng** [xcatliu/mobi.css#86]
Top gap has three gap classes: `.top-gap-big`, `.top-gap` and `.top-gap-0`

May add `.units-gap-0` make units gap be consistent with top gap

**Comment by xcatliu** [comment]
`.top-gap-0` is used to override the default top margin like `<p>`. However, the gaps between each units is 0 by default, so I think it's not necessary to use `.units-gap-0`

**Comment by zheeeng** [comment]
@xcatliu Ok, after one day and I thought twice the design philosophy of mobi.css. I agree with you that it's not necessary to use `.units-gap-0`, but the reason is we actually don't need a zero gap unit style (maybe it is also for `.top-gap-0`).
BTW, the gaps between each units is 7.5px, and the .units-gap-big bring gap 15px. There is no zero gap unit class.
