### ISSUE TITLE
Is this repo no longer maintained?

### ISSUE THREAD

**Issue by xiezipei** [xcatliu/mobi.css#96]
I really like mobi.css, but it seems not any push in the lastest two year.

**Comment by xcatliu** [comment]
This project is already in a stable period, many of my personal projects are based on this.
If you have any feature request or bug report please tell me, I'm ready to support.

**Comment by xiezipei** [comment]
> This project is already in a stable period, many of my personal projects are based on this.
> If you have any feature request or bug report please tell me, I'm ready to support.

I'm very happy to hear that : )
